config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :profile_sitters do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index] do
    member do
      patch '/accepts', to: 'bookings#accepts'
      patch '/decline', to: 'bookings#decline'
      patch '/cancel', to: 'bookings#cancel'
    end
  end

  get '/booking/:id/reply', to: 'bookings#reply'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :profile_sitter
  belongs_to :user
end

app/models/profile_sitter.rb
class ProfileSitter < ApplicationRecord
  has_many :bookings
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  require 'open-uri'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings

  validates :email, presence: true, uniqueness: true
  has_one_attached :photo

  after_create :create_photo

  def create_photo
    unless photo.attached?
      file = URI.open('https://source.unsplash.com/collection/332024/1600x900')
      photo.attach(io: file, filename: 'photo.jpg', content_type: 'image/jpg')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    if params["type"] == "sitter"
      @booking_scope = policy_scope(Booking)
      @bookings = BookingPolicy::Scope.new(current_user, Booking).my_sitter_bookings
    else
      @bookings = policy_scope(Booking).includes(:user).order(created_at: :desc)
    end
  end

  def new
    @booking = Booking.new
    authorize @booking
    @booking.user_id = current_user.id
    @profile_sitter = ProfileSitter.find(params[:profile_sitter_id])
    @profile_start = @profile_sitter.start_date
    @profile_end = @profile_sitter.end_date
    @dates_not_available = Booking.where(profile_sitter: @profile_sitter)
    unless @dates_not_available.nil?
      @disable_date = []
      @dates_not_available.each do |booking|
        dates = {from: booking.start_date.strftime("%Y-%m-%d"), to: booking.end_date.strftime("%Y-%m-%d")}
        @disable_date << dates
      end
    end

  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.user = current_user
    @profile_sitter = ProfileSitter.find(params[:profile_sitter_id])
    @booking.profile_sitter = @profile_sitter
    @booking.status = 'Pending answer'
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def update
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
  end

  def accepts
    skip_authorization
    @booking = Booking.find(params[:id])
    @booking.update(status: 'Accepted')
    redirect_to bookings_path(type: 'sitter')
  end

  def decline
    skip_authorization
    @booking = Booking.find(params[:id])
    @booking.update(status: 'Declined')
    redirect_to bookings_path(type: 'sitter')
  end

  def cancel
    skip_authorization
    @booking = Booking.find(params[:id])
    @booking.destroy
    if params['type'] == 'sitter'
      redirect_to bookings_path(type: 'sitter')
    else
      redirect_to bookings_path
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: :home

  def home
    @profile_sitters = ProfileSitter.all
    @booking = Booking.new
  end
end

app/controllers/profile_sitters_controller.rb
class ProfileSittersController < ApplicationController

  SPECIES = ['dog', 'cat', 'snake', 'spider', 'parrot']
  skip_before_action :authenticate_user!, only: [:index, :show]


  def index

    @profile_sitters = policy_scope(ProfileSitter.includes(:user))

    @markers = @profile_sitters.geocoded.map do |profile_sitter|
      {
        lat: profile_sitter.latitude,
        lng: profile_sitter.longitude,
        info_window: render_to_string(partial: "info_window", locals: { profile_sitter: profile_sitter })
      }
    end

    if params[:query].present?
      # sql_query = "profile_sitters.address ILIKE :query"
      test = params[:query]
      @profile_sitters = @profile_sitters.near(test, 10).geocoded
      @markers = @profile_sitters.geocoded.map do |profile_sitter|
      {
        lat: profile_sitter.latitude,
        lng: profile_sitter.longitude,
        info_window: render_to_string(partial: "info_window", locals: { profile_sitter: profile_sitter })
      }
      end
    else
      @profile_sitters = policy_scope(ProfileSitter)
    end
  end


  def new
    @profile_sitter = ProfileSitter.new
    @user = current_user
    authorize @profile_sitter
  end

  def show
    @profile_sitter = ProfileSitter.find(params[:id])
    authorize @profile_sitter
  end

  def create
    @profile_sitter = ProfileSitter.new(profile_sitter_params)
    @profile_sitter.user = current_user
    authorize @profile_sitter
    if @profile_sitter.save
      redirect_to profile_sitters_path
    else
      render:new
    end
  end

  def destroy
    @profile_sitter = ProfileSitter.find(params[:id])
    @profile_sitter.destroy
    redirect_to profile_sitter_path
  end

  private

  def profile_sitter_params
    params.require(:profile_sitter).permit(:description, :address, :start_date, :end_date, :user_id, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <%# ---- Titre ---- %>
  <div id='booking-title'>
  <% if params["type"] == "sitter" %>
    <h1>My requests</h1>
    <h4><%= pluralize @bookings.size, 'pet owner'%> booked you!</h4>
    <% if @bookings.size == 0 %>
      <p><%= link_to 'Add an availibility!', new_profile_sitter_path, class: "btn btn-ghost top-card" %></p>
    <% end %>
  <% else %>
    <h1>My demands</h1>
    <h4>You booked <%= pluralize @bookings.size, 'sitter'%>!</h4>
    <% if @bookings.size == 0 %>
      <p><%= link_to 'Check sitters available around you!', profile_sitters_path, class: "btn btn-ghost top-card" %></p>
    <% end %>
  <% end %>
  </div>
  <%# ---- Boutton Sitter et Owner ---- %>
  <div class="btn-user">
    <%= link_to "Sitter", bookings_path(type: "sitter"), class: "btn-user-status #{"active" if params["type"] == "sitter"}" %>
    <%= link_to "Owner", bookings_path, class: "btn-user-status #{"active" if params["type"] != "sitter"}" %>
  </div>
  <%# ---- Card bookings ---- %>
  <div class="card-container">
    <% @bookings.each do |booking| %>
      <div class="cards-category m-4">
        <% if booking.user == current_user %>
          <%# ---- Pour voir quand tu as booké un sitter ---- %>
          <% if @bookings.any? %>
            <div class="inner-card">
              <div>
                <%= cl_image_tag booking.profile_sitter.user.photo.key, class: 'avatar-large avatar-border' %>
              </div>
                <h4 class="mb-0 mt-2"><%= booking.profile_sitter.user.first_name %></h4>
            </div>
            <div class="inner-card">
              <p><%= booking.start_date.strftime('%B %d') %></p>
              <p><%= booking.end_date.strftime('%B %d') %></p>
            </div>
            <div class="inner-card" style="height: 145px; width:238px;" id="map"
              data-controller="mapbox"
              data-mapbox-markers-value="<%= [{lat: booking.profile_sitter.latitude, lng: booking.profile_sitter.longitude}].to_json %>"
              data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
            <%#= image_tag 'paris-map.jpg', height: 180, width: 238, id: "map" %>
            <div class="inner-card pb-3 bottom-card">
              <p class='mt-3'><%= booking.status %></p>
            </div>
                <%= link_to cancel_booking_path(booking), method: :patch, class: "btn-choice btn-cancel adjustment", id: 'accepts', title: 'Cancel' do %>
                  <i class="fas fa-ban"></i>
                <% end %>
          <% end %>
        <% else %>
          <%# ---- Pour voir quand tu es booké en tant que sitter ---- %>
          <% if @bookings.any? %>
            <div class="inner-card">
              <div>
                <%= cl_image_tag booking.user.photo.key, class: 'avatar-large avatar-border' %>
              </div>
              <h4 class="mb-0 mt-2"><%= booking.user.first_name %></h4>
            </div>
            <div class="inner-card">
              <p><%= booking.start_date.strftime('%B %d') %></p>
              <p><%= booking.end_date.strftime('%B %d') %></p>
            </div>
            <div>
              <p class="inner-card p-5">You're going to earn <%= booking.profile_sitter.price * (booking.end_date - booking.start_date).to_i %> €!</p>
            </div>
            <%#= image_tag 'paris-map.jpg', height: 180, width: 238, id: "map" %>
            <div class="inner-card pb-3">
              <p class='mt-3'><%= booking.status %></p>
            </div>
            <div class="d-flex accept-decline">
              <% if booking.status == 'Pending answer' %>
                <%= link_to accepts_booking_path(booking), method: :patch, class: "btn-choice btn-accept-decline", id: 'accepts' do %>
                  <i class="fas fa-check"></i>
                <% end %>
                <%= link_to decline_booking_path(booking), method: :patch, class: "btn-choice btn-accept-decline", id: 'declines' do %>
                  <i class="fas fa-times"></i>
                <% end %>
              <% end %>
            <% if booking.status != 'Pending answer' %>
            <%= link_to cancel_booking_path(booking, type: "sitter"), method: :patch, class: "btn-choice btn-cancel", id: 'accepts', title: 'Cancel' do %>
                  <i class="fas fa-ban"></i>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<%# <% end %>

<%# si pas de booking, rajouter une phrase qui dis 'you haven't any booking yet' %>
<%# triple bouton, quand tu cliques sur 'no anwser' ou 'decline' ou 'accepted'
 il change le status avec la string en question --> javascript %>
 <%# quand 'decline' la card se supprime de tous les bookings %>
<%# quand il clique sur 'accept' le booking est rajouté à ceux du pet owner %>

app/views/bookings/new.html.erb
<div class="row py-5 px-4">
  <div class="col-md-5 mx-auto w-80">
<div class="card-container">
  <div class="form-card">
    <div class="title mb-5">
      <h1>Let's book with <%= @profile_sitter.user.first_name %> !</h1>
    </div>
    <%= simple_form_for([@profile_sitter, @booking]) do |f| %>
      <div class="justify-content-center">
              <div class="mb-1">Dates</div>
            <%= f.text_field :start_date, placeholder: "From", input_html: { id: "range_start" }, data: {
          controller: "flatpickr",
          altInput: true,
          flatpickr_mode: 'range',
          flatpickr_date_format: "d/m/Y",
          flatpickr_min_date: @profile_start,
          flatpickr_max_date: @profile_end,
          flatpickr_disable: @disable_date,
        } %>
            <%= f.text_field :end_date, input_html: { id: "range_end" }, placeholder: "To", id: 'secondRangeInput' %>
        </div>
        <div class="d-flex justify-content-center">
      <%= f.button :submit, 'Book', class:'btn-planning', style: 'margin-top: 42px;'%>
        </div>
    <% end %>
  </div>
</div>
 </div>
</div>
<%# limiter les dates a celles qui correspondent au profil sitter %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SitterOnTheWay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
  <%= render 'shared/navbar'  %>
  <%= render 'shared/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-home banner d-flex justify-content-center align-item-center">

  <div class="home-content">
    <div class="home-text text-center">
      <h1> Sitter on the way</h1>
      <h4 class ="mt-4"> Need a sitter for your fantastic pet?</h4>
      <%= render 'shared/searchbar'%>
      <p class = "home-offer">Meet our available sitters close to you and find the perfect match for your <strong><p><span data-controller="typed-js"></span>
</p></strong> </p>
    </div>
  </div>
</div>

app/views/profile_sitters/_info_window.html.erb
<p><strong><%= profile_sitter.user.first_name %> <%= profile_sitter.user.last_name %></strong></p>
<p><%= profile_sitter.address %></p></span>

app/views/profile_sitters/index.html.erb
<%# <style>body {background-color: #E2DBDD;} </style> %>
<div class="index-bar">
  <h3 class="index-title"> Find the perfect sitter for your pet! </h3>

  <div class="left-searchbar input-group">
      <%= render 'shared/searchbar'%>
  </div>

</div>



<div class="index-container">
      <div class="index-cards">
        <div class="cards mt-1">
          <% if @profile_sitters != [] %>
            <% @profile_sitters.each do |profile_sitter| %>
              <div class="card-result-sitter" >
                <% if profile_sitter.user.photo.attached? %>
                  <div class="card-img-top" style="background-image: url('<%= cl_image_path profile_sitter.user.photo.key %>'); background-size: cover;">
                  </div>
                <% else %>
                  <div class="card-img-top" style="background-image: url('https://source.unsplash.com/YozNeHM8MaA'); background-size: cover;">
                  </div>
                <% end %>

                <div class="card-body">
                  <div class="card-body-without-hover">
                    <h5 class="card-result-sitter-title"><%= profile_sitter.user.first_name %> <%= profile_sitter.user.last_name %></h5>
                    <p class="card-result- sitter-text"> <%= profile_sitter.description.slice(0..140) %>...</p>
                    <hr>

                    <div class="card-botton d-flex justify-content-between">
                      <div class="dates">
                        <p>available from <strong><pink><%= profile_sitter.start_date.strftime("%B %d") %></pink></strong> to <strong><pink> <%= profile_sitter.end_date.strftime("%B %d") %> </pink></strong> </p>

                      </div>
                      <div class="price">
                        <p> <pink><strong><%= profile_sitter.price %>€ </pink></strong>/day.
                        </p>
                      </div>
                    </div>

                  </div>
                  <%= link_to "See more", profile_sitter_path(profile_sitter), class:"btn-sitter hide" %>
                </div>
              </div>
            <% end %>
          </div>
          <% else %>
          <h3 class="text-center mb-5">There is no sitter around you</h3>
         <% end %>
      </div>
          <div class="index-map mx-3" style="height: 67vh; width:40%;"
              data-controller="mapbox"
              data-mapbox-markers-value="<%= @markers.to_json %>"
              data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
  </div>

app/views/profile_sitters/new.html.erb
<div class="card-container">
  <div class="form-card p-4 h-50 m-5 d-flex justify-content-center">
  <h2 class="fs-4 mb-5">When will you be available ?</h2>
    <%= simple_form_for([@profile_sitter]) do |f| %>
      <div class="justify-content-center">
        <%= f.input :description %>
        <%= f.input :address %>
        <%= f.input :price %>
        <div class="mb-1">Dates</div>
        <div class="d-flex justify-content-center">
            <%= f.text_field :start_date, placeholder: "From", data: {
          controller: "flatpickr",
          altInput: true,
          flatpickr_mode: 'range',
          flatpickr_date_format: "d/m/Y",
          flatpickr_min_date: Time.zone.now
        } %>
            <%= f.text_field :end_date, placeholder: "To", id: 'secondRangeInput' %>
        </div>
        <div class="d-flex justify-content-center">
          <%= f.button :submit, 'Set new availability', class:'btn-planning m-3'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/profile_sitters/show.html.erb
<div class="row py-5 px-4">
  <div class="col-md-5 mx-auto w-50">
<div class="card-trip">
  <div class="card-trip-infos">
    <div class="d-flex justify-content-between">
      <img src="<%= cl_image_path @profile_sitter.user.photo.key %>" class="avatar-bordered mb-4" />
      <div class="p-3 mb-2">
        <h1><%= @profile_sitter.user.first_name %> <%= @profile_sitter.user.last_name %></h1>
        <p><%= @profile_sitter.address %></p>
      </div>
    </div>
  </div>
      <h2 class="mx-3 text-center fs-4">Available from <%= @profile_sitter.start_date.strftime("%B %d") %> to <%= @profile_sitter.end_date.strftime("%B %d") %>.</br><pink><strong><%= @profile_sitter.price %>€ </pink></strong> per day.</h2>
    <hr>
    <p class="m-3"><%= @profile_sitter.description %></p>
  <div class="d-flex justify-content-center">
    <p><%= link_to "Book", new_profile_sitter_booking_path(@profile_sitter), class: "btn btn-planning m-2 col text-center" %><p>
    <p><%= link_to "Go back", profile_sitters_path, class: "btn btn-back m-2 col text-center" %><p>
  </div>
  <div class="d-flex justify-content-center">
  </div>
  </div>
    <%# <%= @profile_sitter.user.photo.key %>
  </div>
</div>

<div id="booking-form-div"
     data-bookings="<%= @bookings_dates %>">
</div>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
     <%= image_tag 'sotw2.png' %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active" id="home_navbar">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar test dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= image_tag "https://source.unsplash.com/YozNeHM8MaA/800x800", class: "avatar test dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <%end%>
            </a>
              <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <li><%= link_to "My bookings", bookings_path, class: "nav-link" %></li>
                <li><%= link_to "Edit profile",  edit_user_registration_path, class: "nav-link" %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
                <li><%= link_to "New availability", new_profile_sitter_path, class:'nav-link' %></li>
              </ul>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>


<%# <%= link_to (image_tag "loupe.jpeg"), profile_sitters_path class: "test" %>

app/views/shared/_searchbar.html.erb
  <div class="form-outline">
    <div class="input-group">
      <%= form_tag profile_sitters_path, method: :get, class:"search-form mt-3" do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control search-bar",
        placeholder: "Type your adress to find a sitter near you"
        %>
        <%= button_tag(type: "submit", class: "search-button") do %>
          <i class="fas fa-search"></i>
          <span>Search</span>
        <% end %>
      <% end %>
      </div>
  </div>